#ifndef HYPER_FFI_H
#define HYPER_FFI_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct {
  const char *left;
  const char *right;
} PairStr;

PairStr space_find_export(const char *input);

#endif /* HYPER_FFI_H */
